title = "TRIA.os MapLib Documentation" 
GitRepoUrl = "https://github.com/Tria-Studio/Tria-Escape-MapLib"

gitSourceBranch = "master"
changelog = true

[home]
enabled = true
includeReadme = true

[docusaurus]
favicon = "https://coderheck.github.io/assets/TRIAosLogoGradient.png"

[[classOrder]]
section = "MapLib"
classes = ["MapLib"]

[[classOrder]]
section = "Features"
classes = ["Skills", "PlayerUI", "Settings", "Players", "Cleanup"]

[[classOrder]]
section = "Miscellaneous"
classes = ["Janitor"]

[[navbar.items]]
href = "https://discord.gg/tria"
label = "Discord Server"
position = "right"

[[navbar.items]]
href = "https://www.roblox.com/games/6311279644/"
label = "Game"
position = "right"